# Generated by Django 4.0 on 2022-01-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_id_no', models.CharField(max_length=100)),
                ('emp_license_no', models.CharField(max_length=100)),
                ('emp_adress', models.CharField(max_length=100)),
                ('emp_user_id', models.CharField(max_length=50)),
                ('emp_pass', models.CharField(max_length=50)),
                ('emp_co_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
