# Generated by Django 4.0 on 2022-01-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0002_dbuser_addfields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DBuser_AddFields',
        ),
    ]
