# Generated by Django 4.0 on 2022-01-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0003_delete_dbuser_addfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Company_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=50)),
            ],
        ),
    ]
