# Generated by Django 4.0 on 2022-01-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_db_company_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_company_list',
            name='Company_Name',
            field=models.CharField(max_length=100),
        ),
    ]
