# Generated by Django 4.0 on 2022-02-26 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Tourse_and_Travels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.IntegerField()),
                ('vehical_no', models.CharField(max_length=50)),
                ('vehical_type', models.CharField(choices=[('CAR', 'CAR'), ('BUS', 'BUS'), ('TRAVELS', 'TRAVELS'), ('OTHER', 'OTHER')], max_length=50)),
                ('arivel_city', models.CharField(max_length=50)),
                ('arivel_time', models.DateTimeField(auto_now_add=True)),
                ('destination_city', models.CharField(max_length=50)),
                ('destination_time', models.DateTimeField(auto_now=True)),
                ('opning_km', models.IntegerField()),
                ('closing_km', models.IntegerField()),
                ('opning_km_photo', models.ImageField(upload_to='opning_km')),
                ('closing_km_photo', models.ImageField(upload_to='closing_km')),
                ('total_km', models.IntegerField()),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_photo', models.ImageField(null=True, upload_to='customer_photo')),
                ('order_by', models.CharField(max_length=100)),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Driver_Name', to='auth.user')),
            ],
        ),
    ]
