# Generated by Django 4.0 on 2022-02-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='bill_no',
            field=models.IntegerField(null=True),
        ),
    ]
