# Generated by Django 4.0 on 2022-02-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Travels', '0002_alter_db_tourse_and_travels_bill_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='closing_km',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='closing_km_photo',
            field=models.ImageField(null=True, upload_to='closing_km'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='cust_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photo'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='order_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='total_km',
            field=models.IntegerField(null=True),
        ),
    ]
