# Generated by Django 4.0 on 2022-02-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Travels', '0003_alter_db_tourse_and_travels_closing_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Droped', 'Droped')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='cust_photo',
            field=models.ImageField(blank=True, default='static/default.png', null=True, upload_to='customer_photo'),
        ),
    ]
