# Generated by Django 4.0 on 2022-02-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Travels', '0004_db_tourse_and_travels_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='closing_km_photo',
            field=models.ImageField(default='static/default.png', null=True, upload_to='closing_km'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='opning_km_photo',
            field=models.ImageField(default='static/default.png', upload_to='opning_km'),
        ),
    ]
