# Generated by Django 4.0 on 2022-02-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Travels', '0006_db_tourse_and_travels_toll1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_tourse_and_travels',
            old_name='toll1',
            new_name='toll_name_1',
        ),
        migrations.RenameField(
            model_name='db_tourse_and_travels',
            old_name='toll2',
            new_name='toll_name_2',
        ),
        migrations.RenameField(
            model_name='db_tourse_and_travels',
            old_name='toll3',
            new_name='toll_name_3',
        ),
        migrations.RenameField(
            model_name='db_tourse_and_travels',
            old_name='toll4',
            new_name='toll_name_4',
        ),
        migrations.RenameField(
            model_name='db_tourse_and_travels',
            old_name='toll5',
            new_name='toll_name_5',
        ),
        migrations.RenameField(
            model_name='db_tourse_and_travels',
            old_name='toll6',
            new_name='toll_name_6',
        ),
        migrations.RemoveField(
            model_name='db_tourse_and_travels',
            name='toll1_photo',
        ),
        migrations.RemoveField(
            model_name='db_tourse_and_travels',
            name='toll2_photo',
        ),
        migrations.RemoveField(
            model_name='db_tourse_and_travels',
            name='toll3_photo',
        ),
        migrations.RemoveField(
            model_name='db_tourse_and_travels',
            name='toll4_photo',
        ),
        migrations.RemoveField(
            model_name='db_tourse_and_travels',
            name='toll5_photo',
        ),
        migrations.RemoveField(
            model_name='db_tourse_and_travels',
            name='toll6_photo',
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='toll_amount_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='toll_amount_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='toll_amount_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='toll_amount_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='toll_amount_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='toll_amount_6',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
