# Generated by Django 4.0 on 2022-02-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Travels', '0007_rename_toll1_db_tourse_and_travels_toll_name_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='order_by_photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_by'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='order_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
