# Generated by Django 4.0 on 2022-02-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Travels', '0008_db_tourse_and_travels_order_by_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='order_by_photo',
            field=models.ImageField(blank=True, default='static/default.png', null=True, upload_to='order_by'),
        ),
    ]
