# Generated by Django 4.0 on 2022-02-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Travels', '0009_alter_db_tourse_and_travels_order_by_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='diesel_amount_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='diesel_amount_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='diesel_amount_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='diesel_amount_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='diesel 1'),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='diesel 2'),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='diesel 3'),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='diesel 4'),
        ),
    ]
