# Generated by Django 4.0 on 2022-02-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Travels', '0010_db_tourse_and_travels_diesel_amount_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='km_reading_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='km_reading_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='km_reading_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_tourse_and_travels',
            name='km_reading_4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
