# Generated by Django 4.0 on 2022-03-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Travels', '0012_alter_db_tourse_and_travels_diesel_meter_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='closing_km_photo',
            field=models.ImageField(default='static/default.jpg', null=True, upload_to='closing_km'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='cust_photo',
            field=models.ImageField(blank=True, default='static/default.jpg', null=True, upload_to='customer_photo'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_1',
            field=models.ImageField(blank=True, default='static/default.jpg', null=True, upload_to='diesel 1'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_2',
            field=models.ImageField(blank=True, default='static/default.jpg', null=True, upload_to='diesel 2'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_3',
            field=models.ImageField(blank=True, default='static/default.jpg', null=True, upload_to='diesel 3'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_4',
            field=models.ImageField(blank=True, default='static/default.jpg', null=True, upload_to='diesel 4'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='opning_km_photo',
            field=models.ImageField(default='static/default.jpg', upload_to='opning_km'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='order_by_photo',
            field=models.ImageField(blank=True, default='static/default.jpg', null=True, upload_to='order_by'),
        ),
    ]
