# Generated by Django 4.0 on 2022-03-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Travels', '0013_alter_db_tourse_and_travels_closing_km_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='diesel 1'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='diesel 2'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='diesel 3'),
        ),
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='diesel 4'),
        ),
    ]
