# Generated by Django 4.0 on 2022-03-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Travels', '0014_alter_db_tourse_and_travels_diesel_meter_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_1',
            field=models.ImageField(blank=True, height_field=100, max_length=500, null=True, upload_to='diesel 1', width_field=100),
        ),
    ]
