# Generated by Django 4.1.7 on 2023-03-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Travels', '0016_alter_db_tourse_and_travels_diesel_meter_photo_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_tourse_and_travels',
            name='diesel_meter_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='diesel 1'),
        ),
    ]
