# Generated by Django 4.0 on 2022-01-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Load_Unload_Vehical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_Name', models.CharField(max_length=200)),
                ('LR_No', models.CharField(max_length=50)),
                ('Vehical_No', models.CharField(max_length=50)),
                ('From_company', models.CharField(choices=[('Bajaj', 'Bajaj'), ('Simence', 'Simens'), ('Induriance Pvt.Ltd.', 'Induriance Pvt.Ltd.'), ('Wakhard Pharma Ltd.', 'Wakhard Pharma Ltd.'), ('Sanjeev Auto Group', 'Sanjeev Auto Group'), ('Videocon Ltd.', 'Videocon Ltd.')], max_length=50)),
                ('From_File', models.FileField(default=None, max_length=250, upload_to='media/')),
                ('From_Date', models.DateTimeField(auto_now_add=True)),
                ('To_company', models.CharField(choices=[('Bajaj', 'Bajaj'), ('Simence', 'Simens'), ('Induriance Pvt.Ltd.', 'Induriance Pvt.Ltd.'), ('Wakhard Pharma Ltd.', 'Wakhard Pharma Ltd.'), ('Sanjeev Auto Group', 'Sanjeev Auto Group'), ('Videocon Ltd.', 'Videocon Ltd.')], max_length=50)),
                ('To_Date', models.DateTimeField(auto_now=True)),
                ('To_File', models.FileField(default=None, max_length=250, upload_to='media/')),
                ('Receiver', models.CharField(max_length=50)),
                ('Invoice', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
            ],
        ),
    ]
