# Generated by Django 4.0 on 2022-01-12 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_load_unload_vehical',
            old_name='Status',
            new_name='Status_Delivered',
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Status_Pending',
            field=models.CharField(default=datetime.datetime(2022, 1, 12, 2, 44, 10, 769064, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
