# Generated by Django 4.0 on 2022-01-12 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_status_db_load_unload_vehical_status_delivered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_load_unload_vehical',
            old_name='Status_Delivered',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='db_load_unload_vehical',
            name='Status_Pending',
        ),
    ]
