# Generated by Django 4.0 on 2022-01-16 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_rename_driver_name_db_load_unload_vehical_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_load_unload_vehical',
            old_name='first_name',
            new_name='Driver_Name',
        ),
    ]
