# Generated by Django 4.0 on 2022-01-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_rename_first_name_db_load_unload_vehical_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='From_Bins',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='To_Bins',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
