# Generated by Django 4.0 on 2022-01-19 01:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_db_load_unload_vehical_driver_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_load_unload_vehical',
            old_name='From_Bins',
            new_name='Bins',
        ),
        migrations.RemoveField(
            model_name='db_load_unload_vehical',
            name='To_Bins',
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='AOC_Paid',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='AOC_ToPay',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Actual_Weight',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Charged_Weight',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Delivery_At',
            field=models.CharField(default='.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Door_Delivery_Paid',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Door_Delivery_ToPay',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Freight_Paid',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Freight_ToPay',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='From_Adress',
            field=models.CharField(default=datetime.datetime(2022, 1, 19, 1, 24, 19, 527570, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='From_Mobile',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='GRAND_TOTAL_Paid',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='GRAND_TOTAL_ToPay',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='GST_Paid',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='GST_ToPay',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Hamali_Charges_Paid',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Hamali_Charges_ToPay',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Item_Type',
            field=models.CharField(default='Liquid', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Other_Charges_Paid',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Other_Charges_ToPay',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='ST_Charges_Paid',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='ST_Charges_ToPay',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='SUB_TOTAL_Paid',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='SUB_TOTAL_ToPay',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='To_Adress',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='To_Mobile',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Value_Subcharge_Paid',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Value_Subcharge_ToPay',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
