# Generated by Django 4.0 on 2022-01-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_rename_from_bins_db_load_unload_vehical_bins_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_load_unload_vehical',
            old_name='LR_No',
            new_name='From_LR_No',
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Auto_LR_No',
            field=models.IntegerField(null=True),
        ),
    ]
