# Generated by Django 4.0 on 2022-01-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_rename_lr_no_db_load_unload_vehical_from_lr_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='From_Adress',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='To_Adress',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
