# Generated by Django 4.0 on 2022-01-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alter_db_load_unload_vehical_from_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='From_Mobile',
            field=models.IntegerField(default=' '),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='To_Mobile',
            field=models.IntegerField(default=' '),
        ),
    ]
