# Generated by Django 4.0 on 2022-01-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_db_load_unload_vehical_aoc_topay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='Freight_ToPay',
            field=models.IntegerField(default=' ', null=True),
        ),
    ]
