# Generated by Django 4.0 on 2022-01-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_alter_db_load_unload_vehical_from_lr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='From_Mobile',
            field=models.IntegerField(blank=True),
        ),
    ]
