# Generated by Django 4.0 on 2022-01-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_alter_db_load_unload_vehical_aoc_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='Bins',
            field=models.IntegerField(null=True),
        ),
    ]
