# Generated by Django 4.0 on 2022-01-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_alter_db_load_unload_vehical_bins'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='Item_Type',
            field=models.CharField(blank=True, choices=[('Liquid', 'Liquid'), ('item1', 'item1'), ('item2', 'item2')], max_length=50, null=True),
        ),
    ]
