# Generated by Django 4.0 on 2022-01-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0025_db_load_unload_vehical_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='From_Branch_Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='To_Branch_Code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
