# Generated by Django 4.0 on 2022-01-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_db_load_unload_vehical_from_branch_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='E_Way_Bill',
            field=models.CharField(default='', max_length=50),
        ),
    ]
