# Generated by Django 4.0 on 2022-01-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0027_db_load_unload_vehical_e_way_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='E_Way_Bill',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
