# Generated by Django 4.0 on 2022-01-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_alter_db_load_unload_vehical_e_way_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='Delivery_At',
            field=models.CharField(default='NA', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='From_Adress',
            field=models.CharField(default='NA', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='To_Adress',
            field=models.CharField(default='NA', max_length=500, null=True),
        ),
    ]
