# Generated by Django 4.0 on 2022-01-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_alter_db_load_unload_vehical_delivery_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='Delivery_At',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='From_Adress',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='To_Adress',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
