# Generated by Django 4.0 on 2022-01-20 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('AdminPanel', '0004_db_company_list'),
        ('User', '0031_alter_db_load_unload_vehical_aoc_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='Driver_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ram', to='auth.user', verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='From_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_list', to='AdminPanel.db_company_list'),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='To_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminPanel.db_company_list'),
        ),
    ]
