# Generated by Django 4.0 on 2022-01-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_db_company_list'),
        ('User', '0032_alter_db_load_unload_vehical_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='From_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company_Name_List', to='AdminPanel.db_company_list'),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='To_company',
            field=models.CharField(choices=[('Bajaj', 'Bajaj'), ('Simence', 'Simens'), ('Induriance Pvt.Ltd.', 'Induriance Pvt.Ltd.'), ('Wakhard Pharma Ltd.', 'Wakhard Pharma Ltd.'), ('Sanjeev Auto Group', 'Sanjeev Auto Group'), ('Videocon Ltd.', 'Videocon Ltd.')], max_length=500, null=True),
        ),
    ]
