# Generated by Django 4.0 on 2022-01-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminPanel', '0004_db_company_list'),
        ('User', '0034_alter_db_load_unload_vehical_from_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='To_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Simens', to='AdminPanel.db_company_list'),
        ),
    ]
