# Generated by Django 4.0 on 2022-01-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0040_db_load_unload_vehical_gst_paid_per_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='GST_Paid',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='GST_Paid_Per',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='GST_ToPay',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='GST_ToPay_Per',
            field=models.FloatField(blank=True, default='0', null=True),
        ),
    ]
