# Generated by Django 4.0 on 2022-01-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0042_db_contact_us_alter_db_load_unload_vehical_item_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DB_contact_us',
        ),
    ]
