# Generated by Django 4.0 on 2022-01-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0043_delete_db_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=50)),
            ],
        ),
    ]
