# Generated by Django 4.0 on 2022-01-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0044_db_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DB_Contact',
        ),
    ]
