# Generated by Django 4.0 on 2022-01-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0046_db_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_contact_us',
            name='enquiry_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
