# Generated by Django 4.0 on 2022-01-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0047_db_contact_us_enquiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_contact_us',
            name='enquiry_date',
        ),
    ]
