# Generated by Django 4.0 on 2022-01-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0049_db_contact_us_enquiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='From_File',
            field=models.ImageField(upload_to='From_Company/'),
        ),
    ]
