# Generated by Django 4.0 on 2022-01-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0053_alter_db_contact_us_cust_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_contact_us',
            name='cust_message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='db_contact_us',
            name='cust_mobile',
            field=models.IntegerField(),
        ),
    ]
