# Generated by Django 4.0.2 on 2022-02-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0054_alter_db_contact_us_cust_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='From_File2',
            field=models.ImageField(blank=True, default='static/default.png', null=True, upload_to='From_company2/'),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='To_File2',
            field=models.ImageField(blank=True, default='static/default.png', null=True, upload_to='To_company2/'),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='To_File3',
            field=models.ImageField(blank=True, default='static/default.png', null=True, upload_to='To_company3/'),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='To_File4',
            field=models.ImageField(blank=True, default='static/default.png', null=True, upload_to='To_company4/'),
        ),
        migrations.AddField(
            model_name='db_load_unload_vehical',
            name='To_File5',
            field=models.ImageField(blank=True, default='static/default.png', null=True, upload_to='To_company5/'),
        ),
        migrations.AlterField(
            model_name='db_load_unload_vehical',
            name='From_File',
            field=models.ImageField(null=True, upload_to='From_company/'),
        ),
    ]
